apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-grpc-definition
  title: Hello World Service
  description: |
    Sample hello-world-grpc-defintion for IAS Codefest 2022
  links:
    - url: https://www.example.com
      title: ArtVadelay 
      icon: dashboard
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
    # The Sentry organization is stored in the app-config.yaml of the Backstage instance.
    sentry.io/project-slug: sample-service
    cloud.google.com/function-ids: projects/roadie-dev-283705/locations/europe-west1/functions/test-fn-1
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/integration-key: 1cf15c07f6f440e0a8d65b7ce80be834
    snyk.io/org-name: roadie
    snyk.io/project-ids: 63ac09c4-fd65-4f53-b9b2-c31d2dee3291
    backstage.io/kubernetes-id: sample-service
    travis-ci.com/repo-slug: RoadieHQ/sample-service
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=sample-service'
    opsgenie.com/component-selector: sample-service-1
    qameta.io/allure-project: value
spec:
  type: service
  owner: sample-team
  lifecycle: experimental
  system: sample-system
  providesApis:
    - sample-service
  dependsOn:
    - Component:sample-service-2
    - Resource:sample-s3-bucket



